AWSTemplateFormatVersion: 2010-09-09
Description: Team repositories cross-account role

Parameters:
  pChildAccountId:
    Description: Child AWS account ID
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  pEnvironment:
    Description: Environment name
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev
  pTeamName:
    Description: Team name
    Type: String
  pSNSNotificationsEmail:
    Description: List of SNS Notification Email Endpoints
    Type: CommaDelimitedList

Mappings:
  pCodeCommitBranch:
    dev:
      branch: dev
    test:
      branch: test
    prod:
      branch: master

Conditions:
  CrossAccount: !Not [!Equals [!Ref pChildAccountId, !Ref "AWS::AccountId"]]
  IsProduction: !Equals [!Ref pEnvironment, "prod"]

Resources:
  rCodeCommitRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role assumed by CodeBuild/CodePipeline in child AWS account
      Path: /
      RoleName: !Sub sdlf-cicd-team-codecommit-${pEnvironment}-${pTeamName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pChildAccountId}:root
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:CreateApprovalRuleTemplate
                  - codecommit:DeleteApprovalRuleTemplate
                  - codecommit:GetApprovalRuleTemplate
                  - codecommit:ListApprovalRuleTemplates
                  - codecommit:ListRepositories
                  - codecommit:ListRepositoriesForApprovalRuleTemplate
                  - codecommit:UpdateApprovalRuleTemplateContent
                  - codecommit:UpdateApprovalRuleTemplateDescription
                  - codecommit:UpdateApprovalRuleTemplateName
                Resource: "*"
              - Effect: Allow
                Action:
                  - codecommit:Get*
                  - codecommit:Describe*
                  - codecommit:List*
                  - codecommit:GitPull
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource:
                  - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-*
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:ListBucket*
                  - s3:Put*
                Resource:
                  - !Sub arn:aws:s3:::sdlf-cfn-artifacts-${AWS::Region}-${pChildAccountId}
                  - !Sub arn:aws:s3:::sdlf-cfn-artifacts-${AWS::Region}-${pChildAccountId}/*
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                  - kms:List*
                  - kms:Describe*
                Resource: !Sub arn:aws:kms:${AWS::Region}:${pChildAccountId}:key/*
                Condition:
                  ForAllValues:StringLike:
                    aws:PrincipalArn: !Sub "*${pTeamName}*"

  rCodeCommitTriggerRule:
    Condition: CrossAccount
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sdlf-cicd-team-codecommit-${pEnvironment}-${pTeamName}
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-pipeline
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-dataset
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-datalakeLibrary
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-pipLibrary
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-stageA
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-stageB
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-stageC
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !FindInMap [pCodeCommitBranch, !Ref pEnvironment, branch]
      State: ENABLED
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${pChildAccountId}:event-bus/default
          Id: !Sub sdlf-cicd-team-codecommit-${pEnvironment}-${pTeamName}
          RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/sdlf-cicd-foundations-eventbus-${pEnvironment}
  rSNSTopic:
    Condition: IsProduction
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "sdlf-repo-notifications-${pEnvironment}-${pTeamName}"
  rSNSTopicPolicy:
    Condition: IsProduction
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: !Sub "sdlf-${pTeamName}-notifications"
        Version: "2012-10-17"
        Statement:
          - Sid: !Sub "sdlf-${pTeamName}-notifications"
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref rSNSTopic
      Topics:
        - !Ref rSNSTopic
  rSNSTopicSubscription:
    Condition: IsProduction
    Type: Custom::SNSSubscription
    Properties:
      ServiceToken: !ImportValue sdlf-sns-topic-subscription-lambda-arn
      TeamName: !Sub ${pTeamName}
      TopicArn: !Ref rSNSTopic
      SubscriptionEndpoints: !Ref pSNSNotificationsEmail
      SubscriptionProtocol: email
  rPullRequestCreated:
    Condition: IsProduction
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "sdlf-pr-created-${pTeamName}"
      Description: !Sub "Notify ${pTeamName} team of newly created pull request"
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Pull Request State Change
        resources:
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-pipeline
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-dataset
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-datalakeLibrary
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-pipLibrary
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-stageA
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-${pTeamName}-stageB
        detail:
          destinationReference:
            - refs/heads/master
            - master
          event:
            - pullRequestCreated
      State: "ENABLED"
      Targets:
        - Arn: !Ref rSNSTopic
          Id: !Sub "sdlf-${pTeamName}-pull-request-created"
          InputTransformer:
            InputTemplate: !Sub '"<notificationBody>"'
            InputPathsMap:
              notificationBody: $.detail.notificationBody
