AWSTemplateFormatVersion: 2010-09-09
Description: SDLF Foundations in datalake domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rAnycompany:
        Type: awslabs::sdlf::foundations::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pChildAccountId: !Ref AWS::AccountId
            pOrg: anycompany
            pDomain: datalake
            pDeploymentInstance: dev
            pCicdRole: Admin
