AWSTemplateFormatVersion: 2010-09-09
Description: Prerequisites for the rest of SDLF to be deployed/used

Parameters:
  pCustomBucketPrefix:
    Description: S3 Bucket Prefix if different from default. Must be a valid S3 Bucket name
    Type: String
    Default: sdlf
  pDomainAccounts:
    Description: S3 Bucket Prefix if different from default. Must be a valid S3 Bucket name
    Type: CommaDelimitedList

Conditions:
  UseCustomBucketPrefix: !Not [!Equals [!Ref pCustomBucketPrefix, sdlf]]

Resources:
  rBuildLambdaLayersFeatureSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/LambdaLayerBuilder/Enabled
      Type: String
      Value: false
      Description: Add Lambda layer builder infrastructure and pipeline stages

  ######## KMS #########
  rKMSKey:
    Type: AWS::KMS::Key
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Description: KMS key for encryption of CodePipeline artifacts
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow logs access
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Domain Pipelines
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain-crossaccount-pipeline,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Team Pipelines
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-team-crossaccount-pipeline,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Domain Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Team Role Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Module Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"

  rKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/sdlf-cicd-kms-key
      TargetKeyId: !Ref rKMSKey

  rKMSKeySsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/KMS/CICDKeyId
      Type: String
      Value: !GetAtt rKMSKey.Arn
      Description: CICD KMS key

  ######## S3 #########
  rArtifactsBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketName:
        !If [
          UseCustomBucketPrefix,
          !Sub "${pCustomBucketPrefix}-cicd-cfn-artifacts",
          !Sub "sdlf-${AWS::Region}-${AWS::AccountId}-cicd-cfn-artifacts",
        ]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref rKMSKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  rArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rArtifactsBucket
      PolicyDocument:
        Statement:
          - Sid: EnforceTlsRequests
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: False
              NumericLessThan:
                s3:TlsVersion: "1.2"
          - Sid: CrossAccount Domain Pipelines
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain-crossaccount-pipeline,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Team Pipelines
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-team-crossaccount-pipeline,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Domain Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Team Role Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Module Cfn
            Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Team Cfn
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
            Condition:
              "ArnLike":
                "aws:PrincipalArn": !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team-*"
                  - inner: !Join
                    - ":role/sdlf-cicd-team-*,arn:${AWS::Partition}:iam::"
                    - Ref: "pDomainAccounts"

  rArtifactsBucketSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/S3/DevOpsArtifactsBucket
      Type: String
      Value: !Ref rArtifactsBucket
      Description: S3 DevOps Artifacts Bucket
