AWSTemplateFormatVersion: 2010-09-09
Description: Multi-environment CICD team repos resources in shared DevOps account

Parameters:
  pGenericPrefix:
    Description: Generic prefix for resource names
    Type: String
    Default: sdlf
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pEnableMonitoring:
    Description: Build sdlf-monitoring cloudformation module as part of domain pipelines
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Monitoring/Enabled

Conditions:
  EnableMonitoring: !Equals [!Ref pEnableMonitoring, true]

Resources:
  ######## CODECOMMIT #########
  rCicdCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-cicd
      RepositoryDescription: !Sub ${pGenericPrefix}-cicd repository
      RepositoryName: !Sub ${pGenericPrefix}-cicd
      KmsKeyId: !Ref pKMSKey

  rFoundationsCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-foundations
      RepositoryDescription: !Sub ${pGenericPrefix}-foundations repository
      RepositoryName: !Sub ${pGenericPrefix}-foundations
      KmsKeyId: !Ref pKMSKey

  rTeamCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-team
      RepositoryDescription: !Sub ${pGenericPrefix}-team repository
      RepositoryName: !Sub ${pGenericPrefix}-team
      KmsKeyId: !Ref pKMSKey

  rPipelineCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-pipeline
      RepositoryDescription: !Sub ${pGenericPrefix}-pipeline repository
      RepositoryName: !Sub ${pGenericPrefix}-pipeline
      KmsKeyId: !Ref pKMSKey

  rDatasetCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-dataset
      RepositoryDescription: !Sub ${pGenericPrefix}-dataset repository
      RepositoryName: !Sub ${pGenericPrefix}-dataset
      KmsKeyId: !Ref pKMSKey

  rStageACodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-stageA
      RepositoryDescription: !Sub ${pGenericPrefix}-stageA repository
      RepositoryName: !Sub ${pGenericPrefix}-stageA
      KmsKeyId: !Ref pKMSKey

  rStageLambdaCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-stage-lambda
      RepositoryDescription: !Sub ${pGenericPrefix}-stage-lambda repository
      RepositoryName: !Sub ${pGenericPrefix}-stage-lambda
      KmsKeyId: !Ref pKMSKey

  rStageBCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-stageB
      RepositoryDescription: !Sub ${pGenericPrefix}-stageB repository
      RepositoryName: !Sub ${pGenericPrefix}-stageB
      KmsKeyId: !Ref pKMSKey

  rStageGlueCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-stage-glue
      RepositoryDescription: !Sub ${pGenericPrefix}-stage-glue repository
      RepositoryName: !Sub ${pGenericPrefix}-stage-glue
      KmsKeyId: !Ref pKMSKey

  rDatalakeLibraryCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-datalakeLibrary
      RepositoryDescription: !Sub ${pGenericPrefix}-datalakeLibrary repository
      RepositoryName: !Sub ${pGenericPrefix}-datalakeLibrary
      KmsKeyId: !Ref pKMSKey

  rMainCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ./README.md
      RepositoryDescription: !Sub ${pGenericPrefix}-main repository
      RepositoryName: !Sub ${pGenericPrefix}-main
      KmsKeyId: !Ref pKMSKey

  rMonitoringCodeCommit:
    Type: AWS::CodeCommit::Repository
    Condition: EnableMonitoring
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ../sdlf-monitoring
      RepositoryDescription: !Sub ${pGenericPrefix}-monitoring repository
      RepositoryName: !Sub ${pGenericPrefix}-monitoring
      KmsKeyId: !Ref pKMSKey

  rCicdCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/CicdCodeCommit
      Type: String
      Value: !GetAtt rCicdCodeCommit.Name
      Description: Name of the Cicd repository

  rFoundationsCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/FoundationsCodeCommit
      Type: String
      Value: !GetAtt rFoundationsCodeCommit.Name
      Description: Name of the Foundations repository

  rTeamCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/TeamCodeCommit
      Type: String
      Value: !GetAtt rTeamCodeCommit.Name
      Description: Name of the Team repository

  rPipelineCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/PipelineCodeCommit
      Type: String
      Value: !GetAtt rPipelineCodeCommit.Name
      Description: Name of the Pipeline repository

  rDatasetCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/DatasetCodeCommit
      Type: String
      Value: !GetAtt rDatasetCodeCommit.Name
      Description: Name of the Dataset repository

  rStageACodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageACodeCommit
      Type: String
      Value: !GetAtt rStageACodeCommit.Name
      Description: Name of the StageA repository

  rStageLambdaCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageLambdaCodeCommit
      Type: String
      Value: !GetAtt rStageLambdaCodeCommit.Name
      Description: Name of the Stage-Lambda repository

  rStageBCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageBCodeCommit
      Type: String
      Value: !GetAtt rStageBCodeCommit.Name
      Description: Name of the StageB repository

  rStageGlueCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageGlueCodeCommit
      Type: String
      Value: !GetAtt rStageGlueCodeCommit.Name
      Description: Name of the Stage-Glue repository

  rDatalakeLibraryCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/DatalakeLibraryCodeCommit
      Type: String
      Value: !GetAtt rDatalakeLibraryCodeCommit.Name
      Description: Name of the DatalakeLibrary repository

  rMainCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/MainCodeCommit
      Type: String
      Value: !GetAtt rMainCodeCommit.Name
      Description: Name of the main repository

  rMonitoringCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Condition: EnableMonitoring
    Properties:
      Name: /SDLF/CodeCommit/MonitoringCodeCommit
      Type: String
      Value: !GetAtt rMonitoringCodeCommit.Name
      Description: Name of the monitoring repository
