AWSTemplateFormatVersion: "2010-09-09"
Description: Multi-environment CICD team repos resources in shared DevOps account

Parameters:
  pCustomIdentifier:
    Description: Custom identifier for resource names
    Type: String
    Default: sdlf
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pGitPlatform:
    Description: Platform used to host git repositories
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/GitPlatform
  pEnableMonitoring:
    Description: Build sdlf monitoring cloudformation module as part of domain pipelines
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Monitoring/Enabled

Conditions:
  EnableMonitoring: !Equals [!Ref pEnableMonitoring, true]

Resources:
  rCicdGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}cicd
      Private: true
      Visibility: private
      Archived: false

  rFoundationsGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}foundations
      Private: true
      Visibility: private
      Archived: false

  rTeamGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}team
      Private: true
      Visibility: private
      Archived: false

  rPipelineGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}pipeline
      Private: true
      Visibility: private
      Archived: false

  rDatasetGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}dataset
      Private: true
      Visibility: private
      Archived: false

  rStageAGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}stageA
      Private: true
      Visibility: private
      Archived: false

  rStageLambdaGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}stage-lambda
      Private: true
      Visibility: private
      Archived: false

  rStageBGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}stageB
      Private: true
      Visibility: private
      Archived: false

  rStageGlueGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}stage-glue
      Private: true
      Visibility: private
      Archived: false

  rDatalakeLibraryGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}datalakeLibrary
      Private: true
      Visibility: private
      Archived: false

  rMainGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}main
      Private: true
      Visibility: private
      Archived: false

  rMonitoringGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Condition: EnableMonitoring
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub sdlf-${pCustomIdentifier}monitoring
      Private: true
      Visibility: private
      Archived: false

  rCicdGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/CicdGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}cicd # !GetAtt rCicdGitHub.Name
      Description: Name of the Cicd repository

  rFoundationsGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/FoundationsGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}foundations # !GetAtt rFoundationsGitHub.Name
      Description: Name of the Foundations repository

  rTeamGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/TeamGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}team # !GetAtt rTeamGitHub.Name
      Description: Name of the Team repository

  rPipelineGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/PipelineGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}pipeline # !GetAtt rPipelineGitHub.Name
      Description: Name of the Pipeline repository

  rDatasetGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/DatasetGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}dataset # !GetAtt rDatasetGitHub.Name
      Description: Name of the Dataset repository

  rStageAGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/StageAGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stageA # !GetAtt rStageAGitHub.Name
      Description: Name of the StageA repository

  rStageLambdaGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/StageLambdaGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stage-lambda # !GetAtt rStageLambdaGitHub.Name
      Description: Name of the Stage-Lambda repository

  rStageBGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/StageBGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stageB # !GetAtt rStageBGitHub.Name
      Description: Name of the StageB repository

  rStageGlueGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/StageGlueGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stage-glue # !GetAtt rStageGlueGitHub.Name
      Description: Name of the Stage-Glue repository

  rDatalakeLibraryGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/DatalakeLibraryGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}datalakeLibrary # !GetAtt rDatalakeLibraryGitHub.Name
      Description: Name of the DatalakeLibrary repository

  rMainGitHubSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitHub/MainGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}main  # !GetAtt rMainGitHub.Name
      Description: Name of the main repository

  rMonitoringGitHubSsm:
    Type: AWS::SSM::Parameter
    Condition: EnableMonitoring
    Properties:
      Name: /SDLF/GitHub/MonitoringGitHub
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}monitoring # !GetAtt rMonitoringGitHub.Name
      Description: Name of the monitoring repository

Outputs:
  # workaround {{resolve:ssm:}} not returning an array that can be used directly in VpcConfig blocks
  oKmsKey:
    Description: CICD KMS Key
    Value: !Ref pKMSKey