AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Description: Deploy Glue jobs

Parameters:
  pArtifactsBucket:
    Description: The artifactory bucket used by CodeBuild and CodePipeline
    Type: String
  pDomain:
    Description: Name of the data domain (all lowercase, no symbols or spaces)
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/pDomain
  pEnvironment:
    Description: Environment name
    Type: String
    AllowedValues: [dev, test, prod]
  pTeamName:
    Description: Name of the team (all lowercase, no symbols or spaces)
    Type: String
  pGlueJobs:
    Description: List of glue job names
    Type: CommaDelimitedList
    AllowedPattern: "^[a-zA-Z0-9]*$"
  pGitRef:
    Description: Git reference (commit id) with the sources of these glue jobs
    Type: String
  pEnableVpc:
    Description: Deploy SDLF resources in a VPC
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/VPC/Enabled

Conditions:
  GlueJobsNotEmpty: !Not
    - !Equals
      - !Join ["", !Ref pGlueJobs]
      - ""
  RunInVpc: !Equals [!Ref pEnableVpc, true]

Resources:
  rGlueRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Sub /sdlf-${pTeamName}/
      PermissionsBoundary: !Sub "{{resolve:ssm:/SDLF/IAM/${pTeamName}/TeamPermissionsBoundary}}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub sdlf-${pTeamName}-glue-job
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/InfraKeyId}}"
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/DataKeyId}}"
                  - "{{resolve:ssm:/SDLF/KMS/KeyArn}}"

  rGlueConnection:
    Type: AWS::Glue::Connection
    Condition: RunInVpc
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3010
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionProperties: {}
        ConnectionType: NETWORK
        Description: "Network connected to the VPC data source"
        Name: !Sub sdlf-${pTeamName}-glue-conn
        PhysicalConnectionRequirements:
          AvailabilityZone: us-east-1a # this is not taking into account at all, but the property needs to be present anyway
          SecurityGroupIdList: !Split [",", !ImportValue sdlf-cicd-domain-roles-vpc-security-groups]
          SubnetId: !Select
            - "1"
            - !Split [",", !ImportValue sdlf-cicd-domain-roles-vpc-subnets]

  "Fn::ForEach::GlueJobResources":
  - GlueJobName
  - !Ref pGlueJobs
  - "r${GlueJobName}GlueJob":
      Type: AWS::Glue::Job
      Condition: GlueJobsNotEmpty
      Properties:
        Command:
          Name: glueetl
          PythonVersion: "3"
          ScriptLocation: !Sub s3://${pArtifactsBucket}/transforms/${pDomain}/${pEnvironment}/${pTeamName}/${GlueJobName}-${pGitRef}.py
        DefaultArguments:
          "--job-bookmark-option": job-bookmark-disable
          "--enable-glue-datacatalog": "true"
          "--enable-continuous-cloudwatch-log": "true"
          "--enable-continuous-log-filter": "true"
          "--enable-metrics": "true"
        ExecutionProperty:
          MaxConcurrentRuns: 10
        MaxRetries: 0
        MaxCapacity: 2.0
        GlueVersion: "4.0"
        Name: !Sub sdlf-${pTeamName}-${GlueJobName}
        SecurityConfiguration: !Sub "{{resolve:ssm:/SDLF/Glue/${pTeamName}/SecurityConfigurationId}}"
        Role: !Ref rGlueRole
