AWSTemplateFormatVersion: 2010-09-09
Description: Prerequisites for the rest of SDLF to be deployed/used

Parameters:
  pCustomBucketPrefix:
    Description: S3 Bucket Prefix if different from default. Must be a valid S3 Bucket name
    Type: String
    Default: sdlf
  pDomainAccounts:
    Description: List of AWS account ids bootstrapped with SDLF domain roles
    Type: CommaDelimitedList
  pEnableVpc:
    Description: Deploy SDLF resources in a VPC
    Type: String
    Default: false

Conditions:
  UseCustomBucketPrefix: !Not [!Equals [!Ref pCustomBucketPrefix, sdlf]]
  RunInVpc: !Equals [!Ref pEnableVpc, true]
  GovCloudPartition: !Equals
    - !Sub ${AWS::Partition}
    - aws-us-gov

Resources:
  ######## OPTIONAL SDLF FEATURES #########
  # when enabling VPC support, /SDLF/VPC/VpcId, /SDLF/VPC/SecurityGroupIds and /SDLF/VPC/SubnetIds are required too (see Outputs section)
  # both for the devops account and child accounts.
  rVpcFeatureSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/VPC/Enabled
      Type: String
      Value: !Ref pEnableVpc
      Description: Deploy SDLF resources in a VPC

  rBuildLambdaLayersFeatureSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/LambdaLayerBuilder/Enabled
      Type: String
      Value: false
      Description: Add Lambda layer builder infrastructure and pipeline stages

  rGlueJobDeployerFeatureSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GlueJobDeployer/Enabled
      Type: String
      Value: false
      Description: Add Glue job deployer infrastructure and pipeline stages

  ######## KMS #########
  rKMSKey:
    Type: AWS::KMS::Key
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3042
    Properties:
      Description: KMS key for encryption of CodePipeline artifacts
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow logs access
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Pipelines
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-devops-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-devops-crossaccount-pipeline,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-devops-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-devops-crossaccount-pipeline,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Domain Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Team Role Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: CrossAccount Module Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-cfn-modules,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-cfn-modules,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - kms:Decrypt
              - kms:Describe*
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:List*
              - kms:ReEncrypt*
            Resource: "*"

  rKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/sdlf-cicd-kms-key
      TargetKeyId: !Ref rKMSKey

  rKMSKeySsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/KMS/CICDKeyId
      Type: String
      Value: !GetAtt rKMSKey.Arn
      Description: CICD KMS key

  ######## S3 #########
  rArtifactsBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketName:
        !If [
          UseCustomBucketPrefix,
          !Sub "${pCustomBucketPrefix}-cicd-cfn-artifacts",
          !Sub "sdlf-${AWS::Region}-${AWS::AccountId}-cicd-cfn-artifacts",
        ]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref rKMSKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  rArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3042
    Properties:
      Bucket: !Ref rArtifactsBucket
      PolicyDocument:
        Statement:
          - Sid: EnforceTlsRequests
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: False
              NumericLessThan:
                s3:TlsVersion: "1.2"
          - Sid: CrossAccount Pipelines
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-devops-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-devops-crossaccount-pipeline,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-devops-crossaccount-pipeline"
                  - inner: !Join
                    - ":role/sdlf-cicd-devops-crossaccount-pipeline,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Domain Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-domain"
                  - inner: !Join
                    - ":role/sdlf-cicd-domain,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Team Role Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team"
                  - inner: !Join
                    - ":role/sdlf-cicd-team,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
          - Sid: CrossAccount Team Cfn
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*
            Condition:
              "ArnLike": !If
                - GovCloudPartition
                - "aws:PrincipalArn": !Split
                  - ","
                  - !Sub
                    - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team-*"
                    - inner: !Join
                      - ":role/sdlf-cicd-team-*,arn:aws-us-gov:iam::"
                      - Ref: "pDomainAccounts"
                - "aws:PrincipalArn": !Split
                  - ","
                  - !Sub
                    - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-team-*"
                    - inner: !Join
                      - ":role/sdlf-cicd-team-*,arn:aws:iam::"
                      - Ref: "pDomainAccounts"
          - Sid: CrossAccount Module Cfn
            Effect: Allow
            Principal: !If
              - GovCloudPartition
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-cfn-modules,arn:aws-us-gov:iam::"
                    - Ref: "pDomainAccounts"
              - AWS: !Split
                - ","
                - !Sub
                  - "arn:${AWS::Partition}:iam::${inner}:role/sdlf-cicd-cfn-modules"
                  - inner: !Join
                    - ":role/sdlf-cicd-cfn-modules,arn:aws:iam::"
                    - Ref: "pDomainAccounts"
            Action:
              - s3:*
            Resource:
              - !GetAtt rArtifactsBucket.Arn
              - !Sub ${rArtifactsBucket.Arn}/*

  rArtifactsBucketSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/S3/DevOpsArtifactsBucket
      Type: String
      Value: !Ref rArtifactsBucket
      Description: S3 DevOps Artifacts Bucket

Outputs:
  # workaround {{resolve:ssm:}} not returning an array that can be used directly in VpcConfig blocks
  oVpcFeatureSecurityGroupIds:
    Description: List of security group ids that will be attached to Lambda functions and CodeBuild projects
    Value: !If
      - RunInVpc
      - "{{resolve:ssm:/SDLF/VPC/SecurityGroupIds}}"
      - "-"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "vpc-security-groups"]]

  oVpcFeatureSubnetIds:
    Description: List of subnet ids that will be attached to Lambda functions and CodeBuild projects
    Value: !If
      - RunInVpc
      - "{{resolve:ssm:/SDLF/VPC/SubnetIds}}"
      - "-"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "vpc-subnets"]]
