AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Description: Deploy Lambda Layers

Parameters:
  pArtifactsBucket:
    Description: The artifacts bucket used by CodeBuild and CodePipeline
    Type: String
  pLayers:
    Description: List of folder names from layers/ directory
    Type: CommaDelimitedList
    AllowedPattern: "^[a-zA-Z0-9]*$"
  pGitRef:
    Description: Git reference (commit id) with the sources of these layers
    Type: String

Resources:
  ######## LAMBDA LAYERS ########
  "Fn::ForEach::LambdaLayerResources":
  - LayerName
  - !Ref pLayers
  - "r${LayerName}LambdaLayer":
      Type: AWS::Lambda::LayerVersion
      Properties:
        CompatibleRuntimes:
          - python3.12
        Content:
          S3Bucket: !Ref pArtifactsBucket
          S3Key: !Sub sdlf/layers/${LayerName}-${pGitRef}.zip
        Description: !Sub ${LayerName} Lambda Layer
        LayerName: !Sub "sdlf-${LayerName}"
    "r${LayerName}LambdaLayerSsm":
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub "/SDLF/Lambda/Latest${LayerName}Layer"
        Type: String
        Value: !Ref
              "Fn::Sub": r${LayerName}LambdaLayer
        Description: !Sub The ARN of the latest version of the ${LayerName} layer
