AWSTemplateFormatVersion: "2010-09-09"
Description: Resources to be created by the common stack

Parameters:
  pPipelineReference:
    Type: String
    Default: none
  pArtifactsBucket:
    Description: The artifacts bucket used by CodeBuild and CodePipeline
    Type: String
  pDomain:
    Description: Data domain name
    Type: String
  pEnvironment:
    Description: Environment name
    Type: String

Resources:
  rS3ArtifactsBucketDevopsSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /SDLF/S3/${pDomain}/${pEnvironment}/ArtifactsBucket
      Type: String
      Value: !Ref pArtifactsBucket
      Description: !Sub Name of the Artifacts S3 bucket in domain ${pDomain} ${pEnvironment}

Outputs:
  oPipelineReference:
    Description: CodePipeline reference this stack has been deployed with
    Value: !Ref pPipelineReference