AWSTemplateFormatVersion: "2010-09-09"
Description: Multi-environment CICD team repos resources in shared DevOps account

Parameters:
  pCustomIdentifier:
    Description: Custom identifier for resource names
    Type: String
    Default: sdlf
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pEnableMonitoring:
    Description: Build sdlf monitoring cloudformation module as part of domain pipelines
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Monitoring/Enabled

Conditions:
  EnableMonitoring: !Equals [!Ref pEnableMonitoring, true]

Resources:
  ######## GITLAB #########
  # rSdlfGitLabGroup:
  #   Type: GitLab::Groups::Group
  #   Properties:
  #     Name: SDLF
  #     Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rCicdGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}cicd
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rFoundationsGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}foundations
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rTeamGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}team
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rPipelineGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}pipeline
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rDatasetGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}dataset
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rStageAGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}stageA
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rStageLambdaGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}stage-lambda
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rStageBGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}stageB
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rStageGlueGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}stage-glue
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rDatalakeLibraryGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}datalakeLibrary
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rMainGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}main
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rMonitoringGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Condition: EnableMonitoring
    Properties:
      Name: !Sub sdlf-${pCustomIdentifier}monitoring
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rCicdGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/CicdGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}cicd # !GetAtt rCicdGitLab.Name
      Description: Name of the Cicd repository

  rFoundationsGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/FoundationsGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}foundations # !GetAtt rFoundationsGitLab.Name
      Description: Name of the Foundations repository

  rTeamGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/TeamGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}team # !GetAtt rTeamGitLab.Name
      Description: Name of the Team repository

  rPipelineGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/PipelineGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}pipeline # !GetAtt rPipelineGitLab.Name
      Description: Name of the Pipeline repository

  rDatasetGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/DatasetGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}dataset # !GetAtt rDatasetGitLab.Name
      Description: Name of the Dataset repository

  rStageAGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/StageAGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stageA # !GetAtt rStageAGitLab.Name
      Description: Name of the StageA repository

  rStageLambdaGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/StageLambdaGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stage-lambda # !GetAtt rStageLambdaGitLab.Name
      Description: Name of the Stage-Lambda repository

  rStageBGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/StageBGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stageB # !GetAtt rStageBGitLab.Name
      Description: Name of the StageB repository

  rStageGlueGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/StageGlueGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}stage-glue # !GetAtt rStageGlueGitLab.Name
      Description: Name of the Stage-Glue repository

  rDatalakeLibraryGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/DatalakeLibraryGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}datalakeLibrary # !GetAtt rDatalakeLibraryGitLab.Name
      Description: Name of the DatalakeLibrary repository

  rMainGitLabSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/GitLab/MainGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}main # !GetAtt rMainGitLab.Name
      Description: Name of the main repository

  rMonitoringGitLabSsm:
    Type: AWS::SSM::Parameter
    Condition: EnableMonitoring
    Properties:
      Name: /SDLF/GitLab/MonitoringGitLab
      Type: String
      Value: !Sub sdlf-${pCustomIdentifier}monitoring
      Description: Name of the monitoring repository

Outputs:
  # workaround {{resolve:ssm:}} not returning an array that can be used directly in VpcConfig blocks
  oKmsKey:
    Description: CICD KMS Key
    Value: !Ref pKMSKey