AWSTemplateFormatVersion: "2010-09-09"
Description: CICD to deploy in any account SDLF is used

Parameters:
  pCodeBuildSuffix:
    Description: Suffix appended to the CodeBuild project name
    Type: String
    AllowedPattern: '[A-Za-z0-9\-_]{1,139}'
  pCodeBuildAccountId:
    Description: AWS account ID where the CodeBuild project is deployed (with ./deploy-cicd.sh)
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  pCodeBuildBootstrapRole:
    Description: "sdlf-cicd-bootstrap CodeBuild IAM role name"
    Type: String
  pCodeBuildUserRepositoryRole:
    Description: "sdlf-cicd-CodeBuildSuffix CodeBuild IAM role name"
    Type: String

Conditions:
  NotCodeBuildAccount: !Not [!Equals [!Ref pCodeBuildAccountId, !Ref AWS::AccountId]]

Resources:
  rKMSKey:
    Type: AWS::KMS::Key
    Condition: NotCodeBuildAccount
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3042
    Properties:
      Description: SDLF KMS key for encryption of CodeBuild artifacts
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow logs access
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: "*"

  rArtifactsBucket:
    Type: AWS::S3::Bucket
    Condition: NotCodeBuildAccount
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "sdlf-${AWS::Region}-${AWS::AccountId}-${pCodeBuildSuffix}-cicd-cfn-artifacts"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref rKMSKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  rArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: NotCodeBuildAccount
    Properties:
      Bucket: !Ref rArtifactsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${rArtifactsBucket}/*
              - !Sub arn:${AWS::Partition}:s3:::${rArtifactsBucket}
            Condition:
              Bool:
                aws:SecureTransport: False
            Principal: "*"

  rSdlfCicdCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sdlf-cicd-codebuild-${pCodeBuildAccountId}-${pCodeBuildSuffix}
      Description: Role assumed by a Lambda stage in CodePipeline to deploy the Team Role CloudFormation stack
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess # TODO
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pCodeBuildAccountId}:role/${pCodeBuildBootstrapRole}
                - !Sub arn:${AWS::Partition}:iam::${pCodeBuildAccountId}:role/${pCodeBuildUserRepositoryRole}
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: sdlf-codebuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/sdlf-*
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:UpdateStack
                Resource:
                  - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-foundations-*
                  - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-dataset-*
                  - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-pipeline-*
                  - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-team-*
