AWSTemplateFormatVersion: 2010-09-09
Description: CICD resources to handle deployment of a new team (repository)

Parameters:
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pDomain:
    Description: Name of the data domain (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]{2,9}"
  pTeamName:
    Description: Team name
    Type: String
  pMainRepositoriesPrefix:
    Type: String
    Default: sdlf-main-

Resources:
  rTeamMainCodeCommit:
    Type: AWS::CodeCommit::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ./README.md
      RepositoryDescription: !Sub ${pDomain} ${pTeamName} main repository
      RepositoryName: !Sub ${pMainRepositoriesPrefix}-${pDomain}-${pTeamName}
      KmsKeyId: !Ref pKMSKey

  rTeamMainCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /SDLF/CodeCommit/${pTeamName}/MainCodeCommit
      Type: String
      Value: !GetAtt rTeamMainCodeCommit.Name
      Description: !Sub Name of the ${pDomain} ${pTeamName} main repository
